version: "3.9"
services:
  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
  qdrant:
    image: qdrant/qdrant:v1.3.1
    ports:
      - "6333:6333"
  clearml:
    image: allegroai/clearml
    ports:
      - "8008:8008"
